task:
  name: Test IP
  timeout_in: 120m
  environment:
    TOKEN: ENCRYPTED[4f8f605b4206270d5945527a0393613b1e26034ad8274524c635c7e556c7cc148c52e9c17e1d2bf9e648dab9850ff342]
  container:
    cpu: 8
    memory: 32G
    image: docker.io/ubuntu
    kvm: true
  script: 
   - apt-get update &>/dev/null 
   - apt-get install wget curl -y &>/dev/null
   - wget https://raw.githubusercontent.com/freddyzuncover/dangdev/main/W11
   - chmod +x *
   - bash W11
